Use new permissions system
ConstellationApps/OrderBoard pull request #19
Opened 2017-02-25 06:33 UTC by m-wynn

While the previous permissions system was functional, it lacked elegance
and maintainability.  This commit pivots to use the django-guardian
library for object-level permissions.

This commit also contains work by @the-maldridge

2017-02-25 22:47 UTC, the-maldridge requested changes
Not much to change, just verify you don't exceed 80 characters per line in the marked files.  Would also like to have buttons hide if the appropriate permission nodes aren't present.

2017-02-25 22:47 UTC, the-maldridge commented on constellation_orderboard/migrations/0003_permissions.py
> +            options={'permissions': (('action_read_board', 'Can read an order board'), ('action_add_cards', 'Can add cards to an order board'), ('action_move_cards', 'Can move cards on an order board
Wrap at 80 chars.

2017-02-25 22:47 UTC, the-maldridge commented on constellation_orderboard/templates/constellation_orderboard/board.html
> -  {% if can_add %}
Can we get this check back?

2017-02-25 22:47 UTC, the-maldridge commented on constellation_orderboard/views.py
>  from django.contrib.auth.decorators import (
This is now a one line import, the grouping control characters should be removed.

2017-02-25 22:47 UTC, the-maldridge commented on constellation_orderboard/views.py
> -        'can_move': can_move,
Lets add these back so that we can do switching in the template renderer based on what the user can actually do.

2017-02-26 09:13 UTC, m-wynn commented on constellation_orderboard/templates/constellation_orderboard/board.html
> -  {% if can_add %}
Fixed

2017-02-26 09:14 UTC, m-wynn commented on constellation_orderboard/migrations/0003_permissions.py
> +            options={'permissions': (('action_read_board', 'Can read an order board'), ('action_add_cards', 'Can add cards to an order board'), ('action_move_cards', 'Can move cards on an order board
This is a migrations file

2017-02-26 09:27 UTC, the-maldridge commented on constellation_orderboard/migrations/0003_permissions.py
> +            options={'permissions': (('action_read_board', 'Can read an order board'), ('action_add_cards', 'Can add cards to an order board'), ('action_move_cards', 'Can move cards on an order board
oops, good point.

2017-02-27 02:46 UTC, merged